name: websitedemo
org: test
app: websiteApp
component: website
stage: dev

inputs:
  src:
    src: ./src
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: my-bucket
  protocol: https
